package com.arslan.shizuwall.profiles

import androidx.annotation.DrawableRes
import com.arslan.shizuwall.R

object ProfileIcons {

    const val DEFAULT_KEY = "shield"

    private val icons: Map<String, Int> = mapOf(
        "abc" to R.drawable.ic_picon_abc,
        "ac_unit" to R.drawable.ic_picon_ac_unit,
        "account_tree" to R.drawable.ic_picon_account_tree,
        "add" to R.drawable.ic_picon_add,
        "admin_panel_settings" to R.drawable.ic_picon_admin_panel_settings,
        "airplanemode_active" to R.drawable.ic_picon_airplanemode_active,
        "android" to R.drawable.ic_picon_android,
        "animation" to R.drawable.ic_picon_animation,
        "api" to R.drawable.ic_picon_api,
        "app_settings_alt" to R.drawable.ic_picon_app_settings_alt,
        "apps" to R.drawable.ic_picon_apps,
        "archive" to R.drawable.ic_picon_archive,
        "backup" to R.drawable.ic_picon_backup,
        "battery_charging_full" to R.drawable.ic_picon_battery_charging_full,
        "battery_full" to R.drawable.ic_picon_battery_full,
        "battery_saver" to R.drawable.ic_picon_battery_saver,
        "block" to R.drawable.ic_picon_block,
        "bluetooth" to R.drawable.ic_picon_bluetooth,
        "bolt" to R.drawable.ic_picon_bolt,
        "bookmark" to R.drawable.ic_picon_bookmark,
        "brightness_6" to R.drawable.ic_picon_brightness_6,
        "bug_report" to R.drawable.ic_picon_bug_report,
        "build" to R.drawable.ic_picon_build,
        "cable" to R.drawable.ic_picon_cable,
        "cached" to R.drawable.ic_picon_cached,
        "cancel" to R.drawable.ic_picon_cancel,
        "cast" to R.drawable.ic_picon_cast,
        "check_circle" to R.drawable.ic_picon_check_circle,
        "circle" to R.drawable.ic_picon_circle,
        "cleaning_services" to R.drawable.ic_picon_cleaning_services,
        "cloud_download" to R.drawable.ic_picon_cloud_download,
        "cloud_upload" to R.drawable.ic_picon_cloud_upload,
        "code" to R.drawable.ic_picon_code,
        "construction" to R.drawable.ic_picon_construction,
        "contrast" to R.drawable.ic_picon_contrast,
        "dark_mode" to R.drawable.ic_picon_dark_mode,
        "dashboard" to R.drawable.ic_picon_dashboard,
        "data_object" to R.drawable.ic_picon_data_object,
        "delete_sweep" to R.drawable.ic_picon_delete_sweep,
        "delete" to R.drawable.ic_picon_delete,
        "developer_board" to R.drawable.ic_picon_developer_board,
        "developer_mode" to R.drawable.ic_picon_developer_mode,
        "dns" to R.drawable.ic_picon_dns,
        "do_not_disturb_on" to R.drawable.ic_picon_do_not_disturb_on,
        "edit" to R.drawable.ic_picon_edit,
        "electric_bolt" to R.drawable.ic_picon_electric_bolt,
        "energy_savings_leaf" to R.drawable.ic_picon_energy_savings_leaf,
        "extension" to R.drawable.ic_picon_extension,
        "favorite" to R.drawable.ic_picon_favorite,
        "filter_alt" to R.drawable.ic_picon_filter_alt,
        "fingerprint" to R.drawable.ic_picon_fingerprint,
        "flag" to R.drawable.ic_picon_flag,
        "flash_on" to R.drawable.ic_picon_flash_on,
        "folder_open" to R.drawable.ic_picon_folder_open,
        "folder" to R.drawable.ic_picon_folder,
        "gesture" to R.drawable.ic_picon_gesture,
        "gpp_good" to R.drawable.ic_picon_gpp_good,
        "handyman" to R.drawable.ic_picon_handyman,
        "hardware" to R.drawable.ic_picon_hardware,
        "hexagon" to R.drawable.ic_picon_hexagon,
        "hourglass_bottom" to R.drawable.ic_picon_hourglass_bottom,
        "http" to R.drawable.ic_picon_http,
        "install_mobile" to R.drawable.ic_picon_install_mobile,
        "integration_instructions" to R.drawable.ic_picon_integration_instructions,
        "inventory_2" to R.drawable.ic_picon_inventory_2,
        "key" to R.drawable.ic_picon_key,
        "keyboard" to R.drawable.ic_picon_keyboard,
        "label" to R.drawable.ic_picon_label,
        "lan" to R.drawable.ic_picon_lan,
        "launch" to R.drawable.ic_picon_launch,
        "layers" to R.drawable.ic_picon_layers,
        "light_mode" to R.drawable.ic_picon_light_mode,
        "local_fire_department" to R.drawable.ic_picon_local_fire_department,
        "local_offer" to R.drawable.ic_picon_local_offer,
        "lock_open" to R.drawable.ic_picon_lock_open,
        "lock" to R.drawable.ic_picon_lock,
        "memory" to R.drawable.ic_picon_memory,
        "monitor" to R.drawable.ic_picon_monitor,
        "mouse" to R.drawable.ic_picon_mouse,
        "movie" to R.drawable.ic_picon_movie,
        "network_check" to R.drawable.ic_picon_network_check,
        "nfc" to R.drawable.ic_picon_nfc,
        "notifications_off" to R.drawable.ic_picon_notifications_off,
        "notifications" to R.drawable.ic_picon_notifications,
        "numbers" to R.drawable.ic_picon_numbers,
        "open_in_new" to R.drawable.ic_picon_open_in_new,
        "palette" to R.drawable.ic_picon_palette,
        "password" to R.drawable.ic_picon_password,
        "pause" to R.drawable.ic_picon_pause,
        "pentagon" to R.drawable.ic_picon_pentagon,
        "photo_camera" to R.drawable.ic_picon_photo_camera,
        "play_arrow" to R.drawable.ic_picon_play_arrow,
        "power_settings_new" to R.drawable.ic_picon_power_settings_new,
        "privacy_tip" to R.drawable.ic_picon_privacy_tip,
        "public" to R.drawable.ic_picon_public,
        "push_pin" to R.drawable.ic_picon_push_pin,
        "recycling" to R.drawable.ic_picon_recycling,
        "refresh" to R.drawable.ic_picon_refresh,
        "remove" to R.drawable.ic_picon_remove,
        "report" to R.drawable.ic_picon_report,
        "restart_alt" to R.drawable.ic_picon_restart_alt,
        "restore" to R.drawable.ic_picon_restore,
        "rocket_launch" to R.drawable.ic_picon_rocket_launch,
        "router" to R.drawable.ic_picon_router,
        "schema" to R.drawable.ic_picon_schema,
        "screen_rotation" to R.drawable.ic_picon_screen_rotation,
        "screenshot" to R.drawable.ic_picon_screenshot,
        "sd_storage" to R.drawable.ic_picon_sd_storage,
        "search" to R.drawable.ic_picon_search,
        "security" to R.drawable.ic_picon_security,
        "send" to R.drawable.ic_picon_send,
        "settings_suggest" to R.drawable.ic_picon_settings_suggest,
        "settings" to R.drawable.ic_picon_settings,
        "shield" to R.drawable.ic_picon_shield,
        "signal_cellular_alt" to R.drawable.ic_picon_signal_cellular_alt,
        "skip_next" to R.drawable.ic_picon_skip_next,
        "smartphone" to R.drawable.ic_picon_smartphone,
        "sort" to R.drawable.ic_picon_sort,
        "space_dashboard" to R.drawable.ic_picon_space_dashboard,
        "speed" to R.drawable.ic_picon_speed,
        "square" to R.drawable.ic_picon_square,
        "star" to R.drawable.ic_picon_star,
        "stop" to R.drawable.ic_picon_stop,
        "storage" to R.drawable.ic_picon_storage,
        "sync" to R.drawable.ic_picon_sync,
        "system_update" to R.drawable.ic_picon_system_update,
        "tablet_android" to R.drawable.ic_picon_tablet_android,
        "tag" to R.drawable.ic_picon_tag,
        "terminal" to R.drawable.ic_picon_terminal,
        "thermostat" to R.drawable.ic_picon_thermostat,
        "timelapse" to R.drawable.ic_picon_timelapse,
        "timer" to R.drawable.ic_picon_timer,
        "token" to R.drawable.ic_picon_token,
        "touch_app" to R.drawable.ic_picon_touch_app,
        "tune" to R.drawable.ic_picon_tune,
        "tv" to R.drawable.ic_picon_tv,
        "update" to R.drawable.ic_picon_update,
        "usb" to R.drawable.ic_picon_usb,
        "vibration" to R.drawable.ic_picon_vibration,
        "videocam" to R.drawable.ic_picon_videocam,
        "visibility_off" to R.drawable.ic_picon_visibility_off,
        "visibility" to R.drawable.ic_picon_visibility,
        "volume_off" to R.drawable.ic_picon_volume_off,
        "volume_up" to R.drawable.ic_picon_volume_up,
        "vpn_key" to R.drawable.ic_picon_vpn_key,
        "vpn_lock" to R.drawable.ic_picon_vpn_lock,
        "wallpaper" to R.drawable.ic_picon_wallpaper,
        "warning" to R.drawable.ic_picon_warning,
        "webhook" to R.drawable.ic_picon_webhook,
        "whatshot" to R.drawable.ic_picon_whatshot,
        "widgets" to R.drawable.ic_picon_widgets,
        "wifi_off" to R.drawable.ic_picon_wifi_off,
        "wifi" to R.drawable.ic_picon_wifi
    )

    /** Order shown in the picker grid. */
    val keys: List<String> = icons.keys.toList()

    @DrawableRes
    fun resFor(key: String?): Int = icons[key] ?: icons.getValue(DEFAULT_KEY)
}
