name: "🐞 Bug report"
description: "Create a bug report to help us fix issues"
title: "[BUG]"
labels: bug
body:
  - type: textarea
    id: describe
    attributes:
      label: |
        Describe the bug
      description: |
        What did you do to show this bug?
    validations:
      required: true

  - type: textarea
    id: recurrence
    attributes:
      label: |
        To reproduce
      description: |
        Steps to reproduce the problem (example):
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: |
        Screenshots or screen recording
      description: |
        A screenshot or screen recording can help explain the problem.
        If your file is too large for GitHub, compress it (ZIP) or provide a link (e.g., from a file-hosting service).
    validations:
      required: false