name: 🐞 Bug Report
description: Create A Bug Report To Help Us Fix Them
title: "[BUG]"
labels: bug

body:
  - type: textarea
    id: describe
    attributes:
      label: |
        Describe The Bug
      description: |
        What Did You Do To Show This Bug ?
    validations:
      required: true

  - type: textarea
    id: recurrence
    attributes:
      label: |
        To Reproduce
      description: |
        Example of problem reproduction steps:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: |
        Screenshots Or Screen Recording
      description: |
        A ScreenShot Ot Screen Recording is Worth a Thousand Words.
        If Applicable, Drag And Drop Screenshots Or a Screen To Help Explain Your Problem.
        If Your File is Too Big For Github To Accept, Try To Compress it (ZIP file), Or Paste a Link From Other Websites (Like MediaFire).
    validations:
    
